name: untitled
description: "LifeSafeGuard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  flutter_screenutil: ^5.9.3
  dio: ^5.9.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  injectable: ^2.5.1
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  retrofit: ^4.7.1
  fluttertoast: ^8.2.12
  go_router: ^7.1.1
  awesome_dialog: ^3.2.1
  ndialog: ^4.5.0+1
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.2.0
  smooth_page_indicator: ^1.2.1
  country_code_picker: ^3.4.0
  flutter_otp_text_field: ^1.5.1+1
  video_player: ^2.7.0
  flutter_localization: ^0.3.3
  permission_handler:
  video_compress: ^3.1.4
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0
  carousel_slider: ^5.1.1
  flutter_html: ^3.0.0
  url_launcher: ^6.3.2
  photo_view: ^0.15.0
#  ffmpeg_kit_flutter_new: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  ffmpeg_kit_flutter_new: ^4.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - lib/languages/
